/*!
* @file SGHD.phtml
* @brief Code for webpage that displays historical data.
**/

<!DOCTYPE html>
<?php
/*!
* @brief Log in for mysqli server.
**/
 $db = mysqli_connect('localhost','UOG_SGH','test','SGH_TPAQ')
 or die('Error connecting to MySQL server.');
?>
<html>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
@import url('https://fonts.googleapis.com/css?family=IBM+Plex+Sans:500');
body {margin: 20;	
background: #F9FCFA;
font-family: 'IBM Plex Sans', sans-serif;}

table, th, td {
    border: 1px solid #FF9872;
}

.logo {
  float: left;
  padding-top: 4px;
  }

.topnav {
  overflow: hidden;
  color: #F9FCFA;
  background: #8AA884;
  border-style: ridge;
  border-color:#73836F;
}

.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.active {
  background-color: #4CAF50;
  color: white;
}

.topnav .icon {
  display: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 17px;    
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.topnav a:hover, .dropdown:hover .dropbtn {
  background-color:#DAE0D0;
  color: #FF9872;
}

.dropdown-content a:hover {
  background-color: #ddd;
  color: black;
}

.dropdown:hover .dropdown-content {
  display: block;
}

.responsive {
  width: 80%
  height: auto;
}

input[type=text] {
  width: 130px;
  box-sizing: border-box;
  border-style: ridge;
  border-color:#73836F;
  background-color: white;
  background-image: url('Searchicon.png');
  background-position: 8px 8px; 
  background-repeat: no-repeat;
  background-size: 25px 25px;
  padding: 12px 20px 12px 40px;
  -webkit-transition: width 0.4s ease-in-out;
  transition: width 0.4s ease-in-out;

}

input[type=text]:focus {
  width: 100%;
}

@media screen and (max-width: 1000px) {

 .topnav a:not(:first-child), .dropdown .dropbtn {
    display: none;
  }
  .topnav a.icon {
    float: right;
    display: block;
  }
}

@media screen and (max-width: 1000px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive .icon {
    position: absolute;
    right: 0;
    top: 0;
  }

.topnav.responsive a {
    float: none;
    display: block;
    text-align: left;
  }

  .topnav.responsive .dropdown {float: none;}
  .topnav.responsive .dropdown-content {position: relative;}
  .topnav.responsive .dropdown .dropbtn {
    display: block;
    width: 100%;
    text-align: left;
  }

}

.auto-style1 {
	border-width: 0;
	float: left;
	padding-top: 4px;

}
 h1,h3 { display: inline;}

</style>

</head>

<body>

<div class="topnav" id="myTopnav">
	<img src="logo4.png"  height="43.6" width="199.6"alt="logo" class="logo"   /></a>
    <a>&nbsp;</a>
    <a href="SGAU.html">About Us</a>
     <div class="dropdown">
    <button class="dropbtn">Product
      <i class="fa fa-caret-down"></i>
    </button>    <div class="dropdown-content">
      <a href="SGAIM.html">Overview</a>
      <a href="Specs.html">Specs</a>
      <a href="#">Video</a>
    </div>
    </div>

   <a href="#contact">Shop</a>
  <a href="Support.html">Support</a>
      <a href="#contact">Cart</a>
    <div class="dropdown">
    <button class="dropbtn">My Account
      <i class="fa fa-caret-down"></i>
    </button>    <div class="dropdown-content">
      <a href="Status.phtml">Status</a>
      <a href="SGLD.phtml">Live Data</a>
      <a href="SGHD.phtml">Historical Data</a>
      <a href="#">Orders</a>
    </div>
    </div>
     <div class="dropdown">
    <button class="dropbtn">Social Media
      <i class="fa fa-caret-down"></i>
    </button>    <div class="dropdown-content">
      <a href="https://www.instagram.com/uofg_smartgreenhouse/?hl=en">Instagram</a>
      <a href="https://twitter.com/UofG_SmartGreen">Twitter</a>
      <a href="https://www.youtube.com/channel/UCLjnLePXFhfWH4YzIdtP1aw">YouTube</a>
      <a href="https://www.facebook.com/SmartGreenhouse-2309795909300843/?modal=admin_todo_tour">Facebook</a>
    </div>
    </div>
  <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
</div>
<form>
  <input type="text" name="search" placeholder="Search..">
</form>
<font color="#73836F">
    <br/>
    &nbsp;&nbsp;<h1>HISTORICAL DATA</h1><br/>

<?php
	
/*!
* @brief Indicates which table to select data from.
**/
$query = "SELECT * FROM TPAQ";
mysqli_query($db, $query) or die('Error querying database.');
/*!
* @brief Accesses mysqli_query. 
**/
$result = mysqli_query($db, $query);
if($result->num_rows > 0)
{
echo '<table><tr><th>Date & Time</th><th>SOIL MOISTURE</th><th>UV Index</th><th>TEMPERATURE (°C)</th><th>PRESSURE (hPa)</th><th>HUMIDITY (%rH)</th><th>AIR QUALITY (Ohms)</th></tr>';
while ($row = mysqli_fetch_array($result)) {
        echo '<tr><td>' . $row['M'].'/'. $row['D'].'/'.$row['Y'].'&nbsp;'. $row['H'].':'.$row['Min'].':'.$row['S'].'</td><td>'.$row['SM'].'</td><td>'.$row['UV'].'</td><td>'.$row['TEMP'].'</td><td>' .$row['PRES'].'</td><td>'.$row['HUM'].'</td><td>' .$row['GASR'].'</td></tr>';
}
}
?>

      </font>
<script>

function myFunction() {

  var x = document.getElementById("myTopnav");

  if (x.className === "topnav") {

    x.className += " responsive";

  } else {

    x.className = "topnav";

  }

}

</script>



</body>

</html>

