<!DOCTYPE html>
<?php
 $db = mysqli_connect('localhost','UOG_SGH','test','SGH_TPAQ')
 or die('Error connecting to MySQL server.');
?>
<html>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
@import url('https://fonts.googleapis.com/css?family=IBM+Plex+Sans:500');
body {margin: 20;	
background: #F9FCFA;
font-family: 'IBM Plex Sans', sans-serif;}

table, th, td {
    border: 1px solid #73836F;
}

.logo {
  float: left;
  padding-top: 4px;
  }

.topnav {
  overflow: hidden;
  color: #F9FCFA;
  background: #8AA884;
  border-style: ridge;
  border-color:#73836F;
}

.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.active {
  background-color: #4CAF50;
  color: white;
}

.topnav .icon {
  display: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 17px;    
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.topnav a:hover, .dropdown:hover .dropbtn {
  background-color:#DAE0D0;
  color: #FF9872;
}

.dropdown-content a:hover {
  background-color: #ddd;
  color: black;
}

.dropdown:hover .dropdown-content {
  display: block;
}

.responsive {
  width: 100%
  height: auto;
}

input[type=text] {
  width: 130px;
  box-sizing: border-box;
  border-style: ridge;
  border-color:#73836F;
  background-color: white;
  background-image: url('Searchicon.png');
  background-position: 8px 8px; 
  background-repeat: no-repeat;
   background-size: 25px 25px;
  padding: 12px 20px 12px 40px;
  -webkit-transition: width 0.4s ease-in-out;
  transition: width 0.4s ease-in-out;

}
input[type=text]:focus {
  width: 100%;
}
@media screen and (max-width: 1000px) {
  .topnav a:not(:first-child), .dropdown .dropbtn {
    display: none;
  }
  .topnav a.icon {
    float: right;
    display: block;
  }
}
@media screen and (max-width: 1000px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive .icon {
    position: absolute;
    right: 0;
    top: 0;
  }
  .topnav.responsive a {
    float: none;
    display: block;
   text-align: left;

  }

  .topnav.responsive .dropdown {float: none;}

  .topnav.responsive .dropdown-content {position: relative;}

  .topnav.responsive .dropdown .dropbtn {

    display: block;

    width: 100%;

    text-align: left;

  }

}

.auto-style1 {

	border-width: 0;

	float: left;

	padding-top: 4px;

}

h1,h3 { display: inline;}

</style>

</head>

<body>

<div class="topnav" id="myTopnav">
  <a href="index.html" style="padding:0">
	<img src="logo4.png"  height="43.6" width="199.6"alt="logo" class="logo"   /></a>
  <a>&nbsp;</a>  
  <a href="SGAU.html">About Us</a>
     <div class="dropdown">
    <button class="dropbtn">Product
      <i class="fa fa-caret-down"></i>
    </button>    <div class="dropdown-content">
      <a href="SGAIM.html">Overview</a>
      <a href="Specs.html">Specs</a>
      <a href="#">Video</a>
    </div>
    </div>

   <a href="#contact">Shop</a>
  <a href="Support.html">Support</a>
      <a href="#contact">Cart</a>
    <div class="dropdown">
    <button class="dropbtn">My Account
      <i class="fa fa-caret-down"></i>
    </button>    <div class="dropdown-content">
      <a href="Status.phtml">Status</a>
      <a href="SGLD.phtml">Live Data</a>
      <a href="SGHD.phtml">Historical Data</a>
      <a href="#">Orders</a>
    </div>
    </div>
     <div class="dropdown">
    <button class="dropbtn">Social Media
      <i class="fa fa-caret-down"></i>
    </button>    <div class="dropdown-content">
      <a href="https://www.instagram.com/uofg_smartgreenhouse/?hl=en">Instagram</a>
      <a href="https://twitter.com/UofG_SmartGreen">Twitter</a>
      <a href="https://www.youtube.com/channel/UCLjnLePXFhfWH4YzIdtP1aw">YouTube</a>
      <a href="https://www.facebook.com/SmartGreenhouse-2309795909300843/?modal=admin_todo_tour">Facebook</a>
    </div>
    </div>
  <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
</div>
<form>
  <input type="text" name="search" placeholder="Search..">
</form>
<font color="#73836F">
    <br/>
    &nbsp;&nbsp;<h1>LIVE DATA</h1><br/>
      <div><h3>
	 &nbsp; <a href="#chart1">Temperature </a>&nbsp;|&nbsp;<a href="#chart2">Humidity</a>&nbsp;|&nbsp;<a href="#chart3">Air Quality</a>
	 &nbsp;|&nbsp;<a href="#chart4">UV Light</a>&nbsp;|&nbsp;<a href="#chart5">Soil Moisture</a></h3></div> <br/> 
      </font>

<?php

$query = "SELECT * FROM TPAQ ORDER BY ID DESC LIMIT 1 ";
mysqli_query($db, $query) or die('Error querying database.');
$result = mysqli_query($db, $query);
if($result->num_rows > 0)
{

while ($row = mysqli_fetch_array($result)) {
        echo 'Last updated on:&nbsp;' . $row['M'].'/'. $row['D'].'/'.$row['Y'].'&nbsp;'. $row['H'].':'.$row['Min'].':'.$row['S'];
}
}
?>
<?php
$query = 'SELECT D,H, TEMP FROM TPAQ';
$result = mysqli_query($db, $query);
$rows = array();
$table = array();
$table['cols'] = array(
 array(
  'label' => 'Date ', 
  'type' => 'string'
 ),
 array(
  'label' => 'Temperature', 
  'type' => 'number'
 )
);
while($row = mysqli_fetch_array($result))
{
 $sub_array = array();
  $sub_array[] =  array(
      "v" => $row["D"],".", $row["H"]
     );
 $sub_array[] =  array(
      "v" => $row["TEMP"]
     );
 $rows[] =  array(
     "c" => $sub_array
    );
}
$table['rows'] = $rows;
$jsonTable = json_encode($table);
?>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript">
   google.charts.load('current', {'packages':['corechart']});
   google.charts.setOnLoadCallback(drawChart);
   function drawChart()
   {
    var data = new google.visualization.DataTable(<?php echo $jsonTable; ?>);
    var options = {
     title:'Temperature Readings',
     legend:{position:'bottom'},
     vAxis: { title: "Temperature (°C)" },
     hAxis: { title: "Date" },
     chartArea:{width:'75%', height:'65%'},
     colors: ['#FF9872']   
   };
    var chart = new google.visualization.LineChart(document.getElementById('line_chart'));
    chart.draw(data, options);
   }
    </script>
    <style>
  .page-wrapper
  {
  width:1000px;
  margin:0 auto;
  }
  </style>
  <a name="chart1">
  <div class="page-wrapper">
   <br />
   <div id="line_chart" style="width: 100%; height: 400px"></div>
 </div></a>
<?php
$query = 'SELECT D,H, HUM FROM TPAQ';
$result = mysqli_query($db, $query);
$rows = array();
$table1 = array();
$table1['cols'] = array(
 array(
  'label' => 'Date ', 
  'type' => 'string'
 ),
 array(
  'label' => 'Humidity',
  'type' => 'number'
 )
);
while($row = mysqli_fetch_array($result))
{
 $sub_array = array();
  $sub_array[] =  array(
      "v" => $row["D"],".", $row["H"]
     );
 $sub_array[] =  array(
      "v" => $row["HUM"]
     );
 $rows[] =  array(
     "c" => $sub_array
    );
}
$table1['rows'] = $rows;
$jsonTable1 = json_encode($table1);
?>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript">
   google.charts.load('current', {'packages':['corechart']});
   google.charts.setOnLoadCallback(drawChart);
   function drawChart()
   {
    var data = new google.visualization.DataTable(<?php echo $jsonTable1; ?>);
    var options = {
     title:'Humidity Readings',
     legend:{position:'bottom'},
     vAxis: { title: "Humidity (%rH)" },
     hAxis: { title: "Date" },
     chartArea:{width:'75%', height:'65%'},
   };
    var chart = new google.visualization.LineChart(document.getElementById('line_chart1'));
    chart.draw(data, options);
   }
    </script>
   <a name="chart2">
   <div class="page-wrapper">
   <br />
   <div id="line_chart1" style="width: 100%; height: 400px"></div>
   </div>
   </a>
<?php
$query = 'SELECT D,H, GASR FROM TPAQ';
$result = mysqli_query($db, $query);
$rows = array();
$table2 = array();
$table2['cols'] = array(
 array(
  'label' => 'Date ', 
  'type' => 'string'
 ),
 array(
  'label' => 'Air Quality',
  'type' => 'number'
 )
);
while($row = mysqli_fetch_array($result))
{
 $sub_array = array();
  $sub_array[] =  array(
      "v" => $row["D"],".", $row["H"]
     );
 $sub_array[] =  array(
      "v" => $row["GASR"]
     );
 $rows[] =  array(
     "c" => $sub_array
    );
}
$table2['rows'] = $rows;
$jsonTable2 = json_encode($table2);
?>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript">
   google.charts.load('current', {'packages':['corechart']});
   google.charts.setOnLoadCallback(drawChart);
   function drawChart()
   {
    var data = new google.visualization.DataTable(<?php echo $jsonTable2; ?>);
    var options = {
     title:'Air Quality Readings',
     legend:{position:'bottom'},
     vAxis: { title: "Gas Resistance (Ohms)" },
     hAxis: { title: "Date" },
     legend:{position:'bottom'},
     chartArea:{width:'75%', height:'65%'},
     colors: ['#8AA884']   
   };
    var chart = new google.visualization.LineChart(document.getElementById('line_chart2'));
    chart.draw(data, options);
   }

    </script>
    <a name="chart3">
     <div class="page-wrapper">
   <br />
   <div id="line_chart2" style="width: 100%; height: 400px"></div>
  </div>
 </a>
<?php
$query = 'SELECT ID, UV FROM TPAQ';
$result = mysqli_query($db, $query);
$rows = array();
$table3 = array();
$table3['cols'] = array(
 array(
  'label' => 'Date ', 
  'type' => 'number'
 ),
 array(
  'label' => 'UV',
  'type' => 'number'
 )
);
while($row = mysqli_fetch_array($result))
{
 $sub_array = array();
  $sub_array[] =  array(
      "v" => $row["ID"]
     );
 $sub_array[] =  array(
      "v" => $row["UV"]
     );
 $rows[] =  array(
     "c" => $sub_array
    );
}
$table3['rows'] = $rows;
$jsonTable3 = json_encode($table3);
?>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript">
   google.charts.load('current', {'packages':['corechart']});
   google.charts.setOnLoadCallback(drawChart);
   function drawChart()
   {
    var data = new google.visualization.DataTable(<?php echo $jsonTable3; ?>);
    var options = {
     title:'UV Light Readings',
     legend:{position:'bottom'},
     vAxis: { title: "UV Index" },
     hAxis: { title: "Readig no." },
     legend:{position:'bottom'},
     chartArea:{width:'75%', height:'65%'},
     colors: ['violet']   
   };
    var chart = new google.visualization.LineChart(document.getElementById('line_chart3'));
    chart.draw(data, options);
   }

    </script>
    <a name="chart4">
     <div class="page-wrapper">
   <br />
   <div id="line_chart3" style="width: 100%; height: 400px"></div>
  </div>
 </a>
 <?php
$query = 'SELECT ID, SM FROM TPAQ';
$result = mysqli_query($db, $query);
$rows = array();
$table4 = array();
$table4['cols'] = array(
 array(
  'label' => 'Reading no. ', 
  'type' => 'number'
 ),
 array(
  'label' => 'Soil Moisture',
  'type' => 'number'
 )
);
while($row = mysqli_fetch_array($result))
{
 
 $sub_array = array();
 $sub_array[] =  array(
      "v" => $row["ID"]
     ); 
 $sub_array[] =  array(
      "v" => $row["SM"]
     );
 $rows[] =  array(
     "c" => $sub_array
    );
}
$table4['rows'] = $rows;
$jsonTable4 = json_encode($table4);
?>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript">
   google.charts.load('current', {'packages':['corechart']});
   google.charts.setOnLoadCallback(drawChart);
   function drawChart()
   {
    var data = new google.visualization.DataTable(<?php echo $jsonTable4; ?>);
    var options = {
     title:'Soil Moisture Readings',
     legend:{position:'bottom'},
     vAxis: { title: "Soil Moisture" },
     hAxis: { title: "Reading no." },
     legend:{position:'bottom'},
     chartArea:{width:'75%', height:'65%'},
     colors: ['brown']   
   };
    var chart = new google.visualization.LineChart(document.getElementById('line_chart4'));
    chart.draw(data, options);
   }

    </script>
    <a name="chart5">
     <div class="page-wrapper">
   <br />
   <div id="line_chart4" style="width: 100%; height: 500px"></div>
  </div>
 </a>
 
 <script>
function myFunction() {
  var x = document.getElementById("myTopnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}

</script>
</body>
</html>

