<!DOCTYPE html>
<?php
/*! @file Status.phtml
* @brief File that allows for current sensor reading displays.
/*!
* @brief Log in for mysqli server.
**/
 $db = mysqli_connect('localhost','UOG_SGH','test','SGH_TPAQ')
 or die('Error connecting to MySQL server.');
?>
<html>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
@import url('https://fonts.googleapis.com/css?family=IBM+Plex+Sans:500');
body {margin: 20;	
background: #F9FCFA;
font-family: 'IBM Plex Sans', sans-serif;}

table, th, td {
    border: 1px solid #FF9872;
}

.logo {
  float: left;
  padding-top: 4px;
  }

.topnav {
  overflow: hidden;
  color: #F9FCFA;
  background: #8AA884;
  border-style: ridge;
  border-color:#73836F;
}

.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.active {
  background-color: #4CAF50;
  color: white;
}

.topnav .icon {
  display: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 17px;    
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.topnav a:hover, .dropdown:hover .dropbtn {
  background-color:#DAE0D0;
  color: #FF9872;
}

.dropdown-content a:hover {
  background-color: #ddd;
  color: black;
}

.dropdown:hover .dropdown-content {
  display: block;
}

.responsive {
  width: 100%
  height: auto;
}

input[type=text] {
  width: 130px;
  box-sizing: border-box;
  border-style: ridge;
  border-color:#73836F;
  background-color: white;
  background-image: url('Searchicon.png');
  background-position: 8px 8px; 
  background-repeat: no-repeat;
   background-size: 25px 25px;
  padding: 12px 20px 12px 40px;
  -webkit-transition: width 0.4s ease-in-out;
  transition: width 0.4s ease-in-out;

}


input[type=text]:focus {
  width: 100%;
}

@media screen and (max-width: 1000px) {
  .topnav a:not(:first-child), .dropdown .dropbtn {
    display: none;
  }

  .topnav a.icon {
    float: right;
    display: block;
  }

}

@media screen and (max-width: 1000px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive .icon {
    position: absolute;
    right: 0;
    top: 0;

  }

  .topnav.responsive a {
    float: none;
    display: block;
    text-align: left;

  }

  .topnav.responsive .dropdown {float: none;}
  .topnav.responsive .dropdown-content {position: relative;}
  .topnav.responsive .dropdown .dropbtn {
    display: block;
    width: 100%;
    text-align: left;

  }

}

.auto-style1 {
	border-width: 0;
	float: left;
	padding-top: 4px;

 }

h1,h2 { display: inline;}


</style>
</head>
<body>

<div class="topnav" id="myTopnav">
  <a href="index.html" style="padding:0">
	<img src="logo4.png"  height="43.6" width="199.6"alt="logo" class="logo"   /></a>
    <a>&nbsp;</a>
    <a href="SGAU.html">About Us</a>
     <div class="dropdown">
    <button class="dropbtn">Product
      <i class="fa fa-caret-down"></i>
    </button>    <div class="dropdown-content">
      <a href="SGAIM.html">Overview</a>
      <a href="Specs.html">Specs</a>
      <a href="#">Video</a>
    </div>
    </div>

   <a href="#contact">Shop</a>
  <a href="Support.html">Support</a>
      <a href="#contact">Cart</a>
    <div class="dropdown">
    <button class="dropbtn">My Account
      <i class="fa fa-caret-down"></i>
    </button>    <div class="dropdown-content">
      <a href="Status.phtml">Status</a>
      <a href="SGLD.phtml">Live Data</a>
      <a href="SGHD.phtml">Historical Data</a>
      <a href="#">Orders</a>
    </div>
    </div>
     <div class="dropdown">
    <button class="dropbtn">Social Media
      <i class="fa fa-caret-down"></i>
    </button>    <div class="dropdown-content">
      <a href="https://www.instagram.com/uofg_smartgreenhouse/?hl=en">Instagram</a>
      <a href="https://twitter.com/UofG_SmartGreen">Twitter</a>
      <a href="https://www.youtube.com/channel/UCLjnLePXFhfWH4YzIdtP1aw">YouTube</a>
      <a href="https://www.facebook.com/SmartGreenhouse-2309795909300843/?modal=admin_todo_tour">Facebook</a>
    </div>
    </div>
  <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
</div>
<form>
  <input type="text" name="search" placeholder="Search..">
</form>
<font color="#73836F">
    <br/>
    &nbsp;&nbsp;<h1>STATUS</h1>

      
<?php
/*!
* @brief Indicates which table to select data from.
**/
$query = "SELECT * FROM TPAQ ORDER BY ID DESC LIMIT 1" ;
mysqli_query($db, $query) or die('Error querying database.');
/*!
* @brief Accesses mysqli_query. 
**/
$result = mysqli_query($db, $query);
if($result->num_rows > 0)
{
echo '<div><table><tr><th>Measurement</th><th>Latest Value</th><th>Recommended Values</th><th>Manual Operations</th></tr>';
while ($row = mysqli_fetch_array($result)) {
        echo '<tr><td><p style="text-align:center;"><img src="Graphics/SOIL MOISTURE.jpg" width="60%" alt="logo1"/></p></td><td>&nbsp;&nbsp;<h1>'.$row['SM'].'</h1></td><td>&gt;180</td><td>&nbsp;<input type="submit" id="buttonid" value="Start Watering"/><br/><br/>&nbsp;<input type="submit" id="buttonid1" value="Stop Watering"/> </td></tr>';
        echo '<tr><td><p style="text-align:center;"><img src="Graphics/HUMIDITY.jpg" width="60%" alt="logo1"/></p></td><td>&nbsp;&nbsp;<h1>'.$row['HUM'].'&nbsp;%rH</h1></td><td>15-40%</td></tr>';
        echo '<tr><td><p style="text-align:center;"><img src="Graphics/LIGHT.jpg" width="60%" alt="logo1"/></p></td><td>&nbsp;&nbsp;<h1>'.$row['UV'].'</h1></td><td>UV Index&gt;0</td><td>&nbsp;<input type="submit" id="buttonid2" value="Turn On LEDs"/><br/><br/>&nbsp;<input type="submit" id="buttonid3" value="Turn Off LEDs"/> </td></tr>';
	echo '<tr><td><p style="text-align:center;"><img src="Graphics/AIR_QUALITY.jpg" width="60%" alt="logo1"/></p></td><td>&nbsp;&nbsp;<h1>'.$row['GASR'].'&nbsp;ohms &nbsp;</h1></td><td>&gt;15000</td></tr><br/>Last updated on:&nbsp;' . $row['M'].'/'. $row['D'].'/'.$row['Y'].'&nbsp;'. $row['H'].':'.$row['Min'].':'.$row['S'].'</div>';
	echo '<tr><td><p style="text-align:center;"><img src="Graphics/TEMPERATURE.jpg" width="60%" alt="logo1"/></P></td><td>&nbsp;&nbsp;<h1>'.$row['TEMP'].'°C</h1></td><td>15-30°C</td><td>&nbsp;<input type="submit" id="buttonid4" value="Turn On Heat Mat"/><br/><br/>&nbsp;<input type="submit" id="buttonid5" value="Turn Off Heat Mat"/> </td></tr>';
}
}
?>

      </font>
<script>

function myFunction() {
  var x = document.getElementById("myTopnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}

</script>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.2.1.js"></script>

<script>
    <!--
    $(document).ready(function() {
        $('#buttonid').on('click', function(e) {
            e.preventDefault(); // prevent page from reloading.
            $.get('c.php');
        });
    });
    -->
</script>
<script>
    <!--
    $(document).ready(function() {
        $('#buttonid1').on('click', function(e) {
            e.preventDefault(); // prevent page from reloading.
            $.get('coff.php');
        });
    });
    -->
</script>
<script>
    <!--
    $(document).ready(function() {
        $('#buttonid2').on('click', function(e) {
            e.preventDefault(); // prevent page from reloading.
            $.get('ledon.php');
        });
    });
    -->
</script>
<script>
    <!--
    $(document).ready(function() {
        $('#buttonid3').on('click', function(e) {
            e.preventDefault(); // prevent page from reloading.
            $.get('ledoff.php');
        });
    });
    -->
</script>
<script>
    <!--
    $(document).ready(function() {
        $('#buttonid4').on('click', function(e) {
            e.preventDefault(); // prevent page from reloading.
            $.get('/hmon.php');
        });
    });
    -->
</script>
<script>
    <!--
    $(document).ready(function() {
        $('#buttonid5').on('click', function(e) {
            e.preventDefault(); // prevent page from reloading.
            $.get('/hmoff.php');
        });
    });
    -->
</script>
</body>

</html>



